
spring:
  datasource:
    password: hamadani
    url: jdbc:mysql://localhost:3306/online_store?allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
server:
  servlet:
    context-path: /api/v1

logging:
  file:
    name: E:\mini-project\online-store\logger\log.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"
  level:
    root: error 
      
